### ISSUE TITLE
Schema representation

### ISSUE THREAD

**Issue by Lisser** [minvws/nl-kat-octopoes#48]
**Story: Schema representation**
- Load GraphQL DDL from Plugin Repo / Katalogus
  - [x] Validation
  - [x] Load into an internal representation
  - [ ] Transform into Octopoes-ready representation. E.g.:
    - [ ] Backlinks
  - [x] (De)serialization to XTDB for historical preservation

**Comment by Darwinkel** [comment]
I will investigate good methods / strategies for loading the GraphQL schema's into an in-memory representation, for example through data classes or pydantic.

My intuition is that Python-native data classes would be sufficient, provided we build a good validator+unittests to enforce that they match the schemas.

**Comment by Lisser** [comment]
Implemented in https://github.com/minvws/nl-kat-octopoes/pull/46
