### ISSUE TITLE
Expand DDL validation

### ISSUE THREAD

**Issue by Lisser** [minvws/nl-kat-octopoes#81]
- Try to forge a GraphQL DDL schema that breaks things: (e.g.  override built-in types)
- Write unit tests 
- Write validators

Good approach: whitelist approach instead of blacklist approach (disallow everything at first, then introduce functionality)

**Comment by Darwinkel** [comment]
Progress tracker:
- [ ] Write a couple of both syntactically and logically malformed GraphQL DDL schema's (in `ddl/schemas/`)
- [ ] Write unit tests which assert that the malformed schema's are correctly rejected (in `tests/`)
- [ ] Write boolean whitelist validator logic which checks that a schema is valid (in `ddl/ddl.py`)
